# risk/equity_governor.py
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple
import pandas as pd


@dataclass(frozen=True)
class EquityGovernorDecision:
    dd: float
    multiplier: float
    peak_equity: float
    current_equity: float
    reason: str


class EquityGovernor:
    """
    Equity Governor (DEV2)
    Source of truth: equity curve CSV (generated by DEV3 tracker). Expected columns:
      - equity (preferred) OR equity_usd OR balance OR net_liq OR account_equity
    Logic:
      - peak equity = max(equity)
      - current equity = last(equity)
      - drawdown dd = (peak - current) / peak
      - if dd > 10% => multiplier 0.5
        elif dd > 5% => multiplier 0.75
        else => 1.0
      - "new equity high" resets automatically since peak updates.
    """

    def __init__(self, equity_curve_csv: str | Path):
        self.equity_curve_csv = Path(equity_curve_csv)

    def _read_equity_series(self) -> Optional[pd.Series]:
        p = self.equity_curve_csv
        if not p.exists():
            return None
        try:
            df = pd.read_csv(p)
        except Exception:
            return None
        if df is None or df.empty:
            return None

        col = None
        for c in ["equity", "equity_usd", "balance", "net_liq", "account_equity"]:
            if c in df.columns:
                col = c
                break
        if col is None:
            return None

        s = pd.to_numeric(df[col], errors="coerce").dropna()
        if s.empty:
            return None
        return s

    def decide(self) -> EquityGovernorDecision:
        s = self._read_equity_series()
        if s is None or s.empty:
            return EquityGovernorDecision(
                dd=0.0,
                multiplier=1.0,
                peak_equity=float("nan"),
                current_equity=float("nan"),
                reason="NO_EQUITY_FILE",
            )

        current = float(s.iloc[-1])
        peak = float(s.max())
        dd = 0.0 if peak <= 0 else max(0.0, (peak - current) / peak)

        mult = 1.0
        reason = "OK"
        if dd > 0.10:
            mult = 0.5
            reason = "DD_GT_10PCT"
        elif dd > 0.05:
            mult = 0.75
            reason = "DD_GT_5PCT"

        return EquityGovernorDecision(
            dd=float(dd),
            multiplier=float(mult),
            peak_equity=float(peak),
            current_equity=float(current),
            reason=reason,
        )

    def apply(self, risk_multiplier: float) -> Tuple[float, EquityGovernorDecision]:
        d = self.decide()
        try:
            rm = float(risk_multiplier)
        except Exception:
            rm = 1.0
        # Multiply (fail-open): preserve context sizing while throttling on DD
        return rm * float(d.multiplier), d
